[package]
name = "host"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
default-run = "host"

[dependencies]
ergot = { git = "https://github.com/jamesmunns/ergot", rev = "5a5fab8234339ecdc252e18c41ef2676bd6bb091", features = ["nusb-v0_1", "tokio-serial-v5"] }
icd = { path = "../icd" }
tokio = { version = "1", features = ["macros", "process", "rt-multi-thread", "time", "sync", "signal"] }
log = "0.4"
env_logger = "0.11"
postcard-schema = { version = "0.2", features = ["derive"] }
serde = "1.0"
heapless = "0.9"
tun-rs = { version = "2.7.7", features = ["async"] }
nusb = "0.1.14"
clap = { version = "4.5.54", features = ["derive"] }
tokio-serial = "5.4.5"
tokio-util = { version = "0.7.18", features = ["rt"] }
smoltcp = { version = "0.12.0", features = ["medium-ethernet", "proto-ipv4", "proto-dhcpv4", "socket-icmp", "socket-tcp", "socket-dhcpv4", "std", "socket-udp"], default-features = false }
