[package]
edition = "2024"
name = "firmware-c3"
rust-version = "1.95"
version = "0.1.0"
authors = ["Danila Gornushko"]
license = "MIT OR Apache-2.0"

[[bin]]
name = "firmware-c3"
path = "./src/bin/main.rs"
test = false

[[test]]
harness = false
name = "hello_test"

[lib]
test = false

[dependencies]
esp-hal = { git = "https://github.com/okhsunrog/esp-hal", features = ["defmt", "esp32c3", "unstable"], rev = "3a9d8b1ecbcc470e2ce55e494b587f29e985edff" }

esp-rtos = { git = "https://github.com/okhsunrog/esp-hal", features = [
    "defmt",
    "embassy",
    "esp-alloc",
    "esp-radio",
    "esp32c3",
], rev = "3a9d8b1ecbcc470e2ce55e494b587f29e985edff" }

defmt = "1.1.1"
esp-bootloader-esp-idf = { git = "https://github.com/okhsunrog/esp-hal", features = ["defmt", "esp32c3"], rev = "3a9d8b1ecbcc470e2ce55e494b587f29e985edff" }

esp-alloc = { git = "https://github.com/okhsunrog/esp-hal", features = ["defmt"], rev = "3a9d8b1ecbcc470e2ce55e494b587f29e985edff" }
panic-rtt-target = { version = "0.2.0", features = ["defmt"] }
rtt-target = { version = "0.6.2", features = ["defmt"] }

embassy-executor = { version = "0.10.0", features = ["defmt"] }
embassy-time = { version = "0.5.0", features = ["defmt"] }
embassy-futures = "0.1"
embassy-net-driver = "0.2.0"


embedded-io-async-0_7 = { version = "0.7", package = "embedded-io-async" }
esp-radio = { git = "https://github.com/okhsunrog/esp-hal", features = [
    "defmt",
    "esp-alloc",
    "esp32c3",
    "unstable",
    "wifi",
], rev = "3a9d8b1ecbcc470e2ce55e494b587f29e985edff" }

# Ergot and related
ergot = { git = "https://github.com/jamesmunns/ergot", rev = "5a5fab8234339ecdc252e18c41ef2676bd6bb091", features = [
    "embedded-io-async-v0_7",
    "defmt-v1",
] }
bbqueue = { version = "0.7", default-features = false, features = ["maitake-sync-0_3", "critical-section"] }
mutex = { version = "1.0", features = ["impl-critical-section"] }

# ICD
icd = { path = "../icd" }

critical-section = "1.2.0"
static_cell = "2.1.1"
heapless = "0.9.2"
embassy-sync = "0.8.0"
cobs = { version = "0.3.0", default-features = false }

[dev-dependencies]
embedded-test = { version = "0.7.0", features = [
    "defmt",
    "embassy",
    "external-executor",
] }

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
